### ISSUE TITLE
plugin ui on no devices

### ISSUE THREAD

**Issue by bwp91** [rocket-monkey/homebridge-loxone-control#1]
Upon installing the plugin but not yet having the plugin configured, going to the 'discover devices' tab shows a failed to fetch error.

<img width="1440" alt="Screenshot 2024-02-11 at 03 41 34" src="https://github.com/rocket-monkey/homebridge-loxone-control/assets/43026681/b56c7dcb-f3a3-4f4a-a4bc-9b1bbfd313a0">

would be nice if for the case that the plugin hasn't yet been configured this just showed e.g. a <div> saying "no devices" rather than the failed to fetch error, as it may not be obvious to the user the reason for the error

**Comment by rvetere** [comment]
Thanks for reporting this issue. I have solved it by checking if all necessary config parameters are given and i will display a new error message in case:
![Screenshot 2024-02-11 at 19 17 04](https://github.com/rocket-monkey/homebridge-loxone-control/assets/1505976/40ae690b-e738-4946-ae97-9c1d5f77915f)
